name: CI-On-Dispatch

on: repository_dispatch

jobs:

  bump_fairyfly_core:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'fairyfly_core_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(fairyfly-core==).*/fairyfly-core=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump fairyfly-core to $VERSION"
        git push

  bump_fairyfly_therm_standards:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'fairyfly_therm_standards_release'
    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.DEPS_UPDATING }}
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
        sed -i --regexp-extended 's/(fairyfly-therm-standards==).*/fairyfly-therm-standards=='"$CLEAN_VERSION"'/' requirements.txt
    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "fix(deps): Bump fairyfly-therm-standards to $VERSION"
        git push
